resource "proxmox_virtual_environment_file" "test_file" {
  content_type = "vztmpl"
  datastore_id = "hdd"
  node_name = "pve"

  source_file {
    path = "../generate/result/tarball/nixos-system-x86_64-linux.tar.xz"
    file_name = "postgres-nixos.tar.xz"
  }
}

resource "proxmox_virtual_environment_container" "postgresql" {
  node_name = "pve"
  unprivileged = true
  #started = false

  operating_system {
    type = "nixos"
    template_file_id = proxmox_virtual_environment_file.test_file.id
  }

  initialization {
    hostname = "postgresql"
    ip_config {
      ipv4 {
        address = "dhcp"
      }
    }
  }

  disk {
    size = 20
    datastore_id = "local-lvm"
  }

  network_interface {
    name = "eth0"
  }

  features {
    nesting = true
    #keyctl = true
  }
}
resource "local_file" "this" {
    content  = <<-DOC
      # Values generated by terraform for use
      # In ansible script

      tf_lxc_id: ${proxmox_virtual_environment_container.postgresql.id}
      tf_lxc_net_name: ${proxmox_virtual_environment_container.postgresql.network_interface[0].name}
    DOC
    filename = "./tf_vars.yaml"
}
