- name: Run db migrations on created instance
  hosts: localhost
  vars_files:
    - ../terraform/tf_vars.yaml

  tasks:
    - name: Get vars from sops
      community.sops.load_vars:
        file: ../secrets.yaml
        name: secrets

    - name: Login and use the resulting token
      community.hashi_vault.vault_login:
        url: https://vault.home
        role_id: "{{ secrets.vault_role_id }}"
        secret_id: "{{ secrets.vault_secret_id }}"
        auth_method: approle
      register: res

    - name: Retrieve DB credentials from vault
      community.hashi_vault.vault_kv2_get:
        url: https://vault.home
        token: '{{ res | community.hashi_vault.vault_login_token }}'
        engine_mount_point: kv
        auth_method: token
        path: postgres
      register: response

    - name: Gather databases from instance
      community.postgresql.postgresql_info:
        login_password: "{{ response.secret.pass }}"
        db: postgres
        filter: databases
        login_host: "{{ tf_db_host }}"
      register: db_info

    - name: Set databases to run migrations on
      set_fact:
        dbs: "{{ db_info['databases'].keys() | reject('search', 'template1') | list}}"

    - name: Run migrations
      ansible.builtin.command:
        cmd: flyway migrate
      environment:
        FLYWAY_PASSWORD: "{{ response.secret.pass }}"
        FLYWAY_URL: "jdbc:postgresql://{{ tf_db_host }}:5432/{{item }}"
        FLYWAY_USER: postgres
      with_items: "{{ dbs }}"
